#
# Makefile for KTAU with linux-2.4
#

O_TARGET := ktau.o

#export-objs = 

obj-$(CONFIG_KTAU)	:= ktau_misc.o ktau_inst.o ktau_hash.o ktau_proc.o ktau_buffer.o ktau_mmap.o ktau_merge.o ktau_bootopt.o

include $(TOPDIR)/Rules.make
