CFLAGS=-Wall -I/usr/src/linux/include

all: foreign-tcp-connect foreign-tcp-listen foreign-udp-connect foreign-udp-connect-alloc redirect-udp-recv

clean:
	rm foreign-tcp-connect foreign-tcp-listen foreign-udp-connect foreign-udp-connect-alloc redirect-udp-recv

